name:
  Job
  # Controls when the workflow will run
on:
  # Triggers the workflow every day at 5AM
  schedule:
    - cron: "0 5 * * *"
 
jobs:
  cron:
    runs-on: 
      group: intdev
    
    steps:
      - name: Run a test script
        run: /home/tester/run.test
        working-directory: /home/tester
